version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.23.8
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES:
      TRANSFORMERS_INFERENCE_API: 'http://transformers:8080'
      GRPC_ENABLED: 'true'
      CLUSTER_HOSTNAME: 'node1'
    depends_on:
      - transformers

  transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    restart: unless-stopped
    
    ports:
      - "8081:8080"
    environment:
      ENABLE_CUDA: '0'  # Set to '1' if you have GPU support